seed: 1337

data:
  data_root: data/SpeechCommands
  sample_rate: 16000
  num_samples: 16000
  silence_ratio: 0.05

features:
  sample_rate: 16000
  n_fft: 400
  hop_length: 160
  win_length: 400
  n_mels: 40
  f_min: 20
  f_max: 7600
  normalize: true

model:
  name: tc_resnet
  num_classes: 12
  n_mels: 40
  channels: 48
  num_blocks: 4
  kernel_size: 9
  dropout: 0.1

train:
  batch_size: 1024
  num_workers: 8
  pin_memory: true
  persistent_workers: true
  prefetch_factor: 4
  learning_rate: 0.0005
  weight_decay: 0.0001
  device: cuda:0
  use_cudnn_benchmark: true
  use_weighted_sampler: true
  use_class_weighted_loss: false
